In [ ]:
import pandas as pd
import numpy as np
import os

path_data='/content/drive/MyDrive/data'
lbl_binary=list()
lbl_20_class=list()
data=[]
for folder in os.listdir(path_data):
    path_in=os.path.join(path_data,folder)
    if not os.path.isdir(path_in):
        continue  
    for sub_folder in os.listdir(path_in):
        
        print('---------{0}------------'.format(sub_folder))
        path_in2=os.path.join(path_in,sub_folder)
        if not os.path.isdir(path_in2): 
            continue  
        for file_name in os.listdir(path_in2):
            lbl_one=file_name[:-4]
            print(file_name[:-4])
            path_file=os.path.join(path_in2,file_name)
            txt_data=np.array(pd.read_csv(path_file, delim_whitespace=True))
            txt_data=txt_data[:,1:]
            data.extend(txt_data)
            lbl_all=((lbl_one+',')*txt_data.shape[0]).split(',')[:-1]
            lbl_20_class.extend(lbl_all)
            print(txt_data.shape)


---------aggressive------------
Slapping
(4223, 27)
Pushing
(3413, 27)
Pulling
(4235, 27)
Headering
(4013, 27)
Frontkicking
(3324, 27)
Sidekicking
(4193, 27)
Punching
(3419, 27)
Kneeing
(2977, 27)
Hamering
(3574, 27)
Elbowing
(2804, 27)
---------normal------------
Standing
(4106, 27)
Running
(3032, 27)
Hugging
(4103, 27)
Clapping
(3045, 27)
Walking
(3087, 27)
Seating
(3763, 27)
Jumping
(2946, 27)
Handshaking
(3078, 27)
Bowing
(3751, 27)
Waving
(6416, 27)
---------normal------------
Hugging
(4335, 27)
Standing
(3838, 27)
Seating
(4244, 27)
Walking
(6373, 27)
Running
(4269, 27)
Jumping
(4054, 27)
Bowing
(4272, 27)
Handshaking
(4197, 27)
Waving
(4305, 27)
Clapping
(3952, 27)
---------aggressive------------
Headering
(3706, 27)
Slapping
(6519, 27)
Punching
(4232, 27)
Hamering
(6242, 27)
Frontkicking
(4146, 27)
Sidekicking
(4174, 27)
Elbowing
(4119, 27)
Kneeing
(5516, 27)
Pushing
(4260, 27)
Pulling
(6399, 27)
---------normal------------
Walking
(1685, 27)
Seating
(2325, 27)
Jumping
(1099, 2

# PreProcessing

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import numpy as np


encoder = LabelEncoder()
lbl_20_class = np.array(lbl_20_class)
lbl_20_class = encoder.fit_transform(lbl_20_class.reshape(-1, 1))


scaler = StandardScaler()
data = scaler.fit_transform(data)

print(lbl_20_class)

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[17 17 17 ...  0  0  0]


# Normalization

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

data = np.array(data)
scaler = MinMaxScaler()
normalized_data = scaler.fit_transform(data)
print(normalized_data)

[[0.59446825 0.58998753 0.79865844 ... 0.58200663 0.6679986  0.09719377]
 [0.59446825 0.58998753 0.79865844 ... 0.58200663 0.6679986  0.09719377]
 [0.59446825 0.58998753 0.79865844 ... 0.58200663 0.6679986  0.09719377]
 ...
 [0.40051119 0.52083641 0.69157292 ... 0.31301366 0.60202672 0.23764979]
 [0.40051119 0.52083641 0.69157292 ... 0.310808   0.60224366 0.23757155]
 [0.40051119 0.52083641 0.69157292 ... 0.310808   0.60224366 0.23757155]]


# Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

Data_main = np.array(data)
Data_lable = np.array(lbl_20_class)



from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Data_main, Data_lable, test_size=0.2, random_state=42)


dtreg = DecisionTreeRegressor(random_state=42)
dtreg.fit(X_train, y_train)


y_pred = dtreg.predict(X_test)
print("R-squared score:", r2_score(y_test, y_pred))

R-squared score: 0.9986516026708403


# Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


X_train, X_test, y_train, y_test = train_test_split(Data_main, Data_lable, test_size=0.2, random_state=42)


nb = GaussianNB()
nb.fit(X_train, y_train)


y_pred = nb.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.4135347042639854


# Logical Regression

In [ ]:
from sklearn.linear_model import LinearRegression


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Data_main, Data_lable, test_size=0.2, random_state=42)

linreg = LinearRegression()
linreg.fit(X_train, y_train)


y_pred = linreg.predict(X_test)
from sklearn.metrics import r2_score
print("R-squared score:", r2_score(y_test, y_pred))


R-squared score: 0.13673811329393648


# HyperParameter Tuning On DT


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint


param_dist = {'max_depth': randint(2, 10),
              'min_samples_split': randint(2, 10),
              'min_samples_leaf': randint(1, 8),
              'max_features': [None, 'sqrt', 'log2']}

dtreg = DecisionTreeRegressor(random_state=42)


random_dtreg = RandomizedSearchCV(estimator=dtreg, param_distributions=param_dist, n_iter=50, cv=3, random_state=42, scoring='r2')


random_dtreg.fit(X_train, y_train)

print("Best hyperparameters:", random_dtreg.best_params_)
print("Best score:", random_dtreg.best_score_)


y_pred = random_dtreg.predict(X_test)


print("R-squared score:", r2_score(y_test, y_pred))


Best hyperparameters: {'max_depth': 9, 'max_features': None, 'min_samples_leaf': 1, 'min_samples_split': 5}
Best score: 0.6501079870858814
R-squared score: 0.6741600701422303


# HyperParameter Tuning On Lr

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression


linreg = LinearRegression()

param_grid = {
    "fit_intercept": [True, False],
    "copy_X": [True, False],
    "positive": [True, False],
    "n_jobs": [-1, None],
}

grid_search = GridSearchCV(linreg, param_grid, cv=5)

grid_search.fit(X_train, y_train)

best_linreg = grid_search.best_estimator_
y_pred = best_linreg.predict(X_test)
from sklearn.metrics import r2_score
print("R-squared score:", r2_score(y_test, y_pred))


R-squared score: 0.13673811329393648
